# Welcome to Jekyll!
#

# Site settings
title: Magdalene MCR
description: Garding ta Foy since 1542
owner: Craig Russell # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: ctr26@cam.ac.uk
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mcr.magd.cam.ac.uk" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/MCR_Magdalene
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mcr.it@magd.cam.ac.uk
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
